const $ = s => document.querySelector(s);
const DEF = {title:"",premise:"",genre:"Fantasy",tone:"Dark, atmospheric",pov:"Third person limited",tense:"Past",setting:"",rules:"",style:"",words:1200,characters:[],outline:[],chapters:[]};
let p = {...DEF, ...JSON.parse(localStorage.getItem("sf_project") || "{}")};
const save = () => localStorage.setItem("sf_project", JSON.stringify(p));
const esc = s => String(s ?? "").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/"/g,"&quot;");
const status = t => $("#status").textContent = t;
function wordCount(text){const s=String(text||"").trim();return s?s.split(/\s+/).length:0;}
function addChapters(){const n=Math.max(1,Math.min(60,+$("#nch").value||8));while(p.outline.length<n){const number=p.outline.length+1;p.outline.push({title:`Chapter ${number}`,summary:""});}while(p.outline.length>n){p.outline.pop();p.chapters.pop();}save();render();status(`${n} chapter${n===1?"":"s"} ready to write.`);}
function addChapter(){p.outline.push({title:`Chapter ${p.outline.length+1}`,summary:""});save();render();}
function removeChapter(i){p.outline.splice(i,1);p.chapters.splice(i,1);p.outline.forEach((o,k)=>{if(!o.title||/^Chapter \d+$/.test(o.title))o.title=`Chapter ${k+1}`;});save();render();}
function render(){
 document.querySelectorAll("[data-k]").forEach(el=>el.value=p[el.dataset.k]??"");
 $("#chars").innerHTML=p.characters.map((c,i)=>`<div class="item"><input data-l="characters" data-i="${i}" data-f="name" placeholder="Name" value="${esc(c.name)}"><input data-l="characters" data-i="${i}" data-f="role" placeholder="Role (hero, rival...)" value="${esc(c.role)}"><textarea data-l="characters" data-i="${i}" data-f="description" rows="2" placeholder="Looks, personality, backstory">${esc(c.description)}</textarea><button data-act="delChar" data-i="${i}">Remove</button></div>`).join("");
 $("#outline").innerHTML=p.outline.map((o,i)=>`<div class="item"><b>Chapter ${i+1}</b><input data-l="outline" data-i="${i}" data-f="title" placeholder="Chapter title" value="${esc(o.title)}"><textarea data-l="outline" data-i="${i}" data-f="summary" rows="3" placeholder="What happens in this chapter?">${esc(o.summary)}</textarea><button data-act="delCh" data-i="${i}">Remove chapter</button></div>`).join("");
 $("#chapters").innerHTML=p.outline.map((o,i)=>{const c=p.chapters[i]||{text:""};return `<div class="item"><b>Chapter ${i+1}: ${esc(o.title||`Chapter ${i+1}`)}</b><textarea class="chapter" data-ch="${i}" placeholder="Start writing here...">${esc(c.text)}</textarea><p class="hint" id="count${i}">${wordCount(c.text)} words</p></div>`;}).join("");
}
function download(name,text){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:"text/plain;charset=utf-8"}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
document.addEventListener("input",e=>{const t=e.target;if(t.dataset.k)p[t.dataset.k]=t.type==="number"?+t.value:t.value;else if(t.dataset.l)p[t.dataset.l][+t.dataset.i][t.dataset.f]=t.value;else if(t.dataset.ch!==undefined){const i=+t.dataset.ch;if(!p.chapters[i])p.chapters[i]={text:""};p.chapters[i].text=t.value;const counter=$(`#count${i}`);if(counter)counter.textContent=`${wordCount(t.value)} words`;}save();});
document.addEventListener("click",e=>{const b=e.target.closest("[data-act]");if(!b)return;const i=+b.dataset.i,act=b.dataset.act;if(act==="addChar"){p.characters.push({name:"",role:"",description:""});save();render();}else if(act==="addCh")addChapter();else if(act==="delChar"){p.characters.splice(i,1);save();render();}else if(act==="delCh")removeChapter(i);else if(act==="outline")addChapters();else if(act==="exportMd"){const story=`# ${p.title||"Untitled Story"}\n\n`+p.outline.map((o,k)=>`## Chapter ${k+1}: ${o.title||`Chapter ${k+1}`}\n\n${p.chapters[k]?.text||""}`).join("\n\n");download((p.title||"story")+".md",story);status("Story downloaded.");}else if(act==="exportJson"){download((p.title||"story")+".json",JSON.stringify(p,null,2));status("Project saved.");}else if(act==="reset"&&confirm("Start a new story? Save your project first.")){p=JSON.parse(JSON.stringify(DEF));save();render();status("New story started.");}});
$("#load").addEventListener("change",async e=>{try{p={...DEF,...JSON.parse(await e.target.files[0].text())};save();render();status("Project loaded.");}catch{status("Could not load that project file.");}});
render();
